-- Run this script in Supabase Dashboard > SQL Editor.
-- It supports both a fresh setup and migration from the previous feedback schema.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text,
  relation text,
  device text,
  message text not null,
  created_at timestamp with time zone not null default now()
);

-- Upgrade an existing table created by the previous version.
alter table public.feedback add column if not exists relation text;
alter table public.feedback add column if not exists device text;

-- Preserve any existing rows before making the new fields required.
update public.feedback set relation = 'other' where relation is null;
update public.feedback set device = 'other' where device is null;

alter table public.feedback alter column relation set not null;
alter table public.feedback alter column device set not null;

-- Remove fields that are no longer part of the assignment.
alter table public.feedback drop column if exists email;
alter table public.feedback drop column if exists category;
alter table public.feedback drop column if exists rating;

-- Recreate validation constraints so this script can be run more than once.
alter table public.feedback drop constraint if exists feedback_name_length;
alter table public.feedback drop constraint if exists feedback_relation_check;
alter table public.feedback drop constraint if exists feedback_device_check;
alter table public.feedback drop constraint if exists feedback_message_length;

alter table public.feedback
  add constraint feedback_name_length
    check (name is null or char_length(name) <= 50),
  add constraint feedback_relation_check
    check (relation in ('classmate', 'friend', 'teacher', 'family', 'visitor', 'other')),
  add constraint feedback_device_check
    check (device in ('mobile', 'tablet', 'desktop', 'other')),
  add constraint feedback_message_length
    check (char_length(btrim(message)) between 5 and 800);

alter table public.feedback enable row level security;

-- Visitors may submit feedback, but they cannot read, edit, or delete it.
drop policy if exists "Anyone can submit feedback" on public.feedback;
create policy "Anyone can submit feedback"
on public.feedback
for insert
to anon
with check (true);

-- Keep table privileges narrow. RLS still applies in addition to these grants.
revoke all on table public.feedback from anon;
grant insert on table public.feedback to anon;
grant usage, select on sequence public.feedback_id_seq to anon;
